git:
  overrideGpg: true
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#25be6a"
      - "bold"
    inactiveBorderColor:
      - "#78a9ff"
    searchingActiveBorderColor:
      - "#08bdba"
      - "bold"
    optionsTextColor:
      - "#78a9ff"
    selectedLineBgColor:
      - "#353535"
    cherryPickedCommitFgColor:
      - "#78a9ff"
    cherryPickedCommitBgColor:
      - "#be95ff"
    markedBaseCommitFgColor:
      - "#78a9ff"
    markedBaseCommitBgColor:
      - "#08bdba"
    unstagedChangesColor:
      - "#ee5396"
    defaultFgColor:
      - "#f2f4f8"
